/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './Pagination.module.css';

function Pagination() {
  return (
    <nav className={styles.pagination} aria-label="Page navigation">
      <button className={styles.pageButton} aria-label="Previous page">
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/24e8d05b4251d8ca029ec0ef83241d69b3a7003988d42322b16bb94dcc991141?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="" />
      </button>
      <button className={styles.pageNumber}>1</button>
      <button className={styles.pageNumber}>2</button>
      <button className={styles.pageNumber}>3</button>
      <button className={styles.pageNumber}>4</button>
      <button className={styles.pageNumber}>5</button>
      <button className={styles.pageNumber}>6</button>
      <button className={styles.pageNumber}>7</button>
      <button className={styles.pageButton} aria-label="Next page">
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/4eb77b5c3636bac2f42c511716c00a53c2a6ed4fad36da447d483b4fea603596?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="" />
      </button>
    </nav>
  );
}

export default Pagination;