/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './Filter.module.css';

function PriceFilter() {
  return (
    <div className={styles.filterItem}>
      <span>Price:</span>
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/3da90a589e5c5ff991b48d02d79bb7cfef52d91bfc7202fbb5fa147e62a660d2?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="" className={styles.filterIcon} />
    </div>
  );
}

export default PriceFilter;