/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './SearchNFT.module.css';
import NFTCard from './NFTCard';
import CategoryFilter from './CategoryFilter';
import PriceFilter from './PriceFilter';
import TimeFilter from './TimeFilter';
import StatusFilter from './StatusFilter';
import Pagination from './Pagination';
import Footer from './Footer';

const nftData = [
  { id: 1, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c7c6b906f13c410f37641136165451e61f8bd4af0c1deb1f99edc3d195f774b4?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 2, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7f832ce42e9c4f9ff10f19af7ff2c93e4f6092bb17ab8d9e8d2525089c37ec96?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 3, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/5d3529c6cf9c0a09ed96abb3998dc6643e2946a4a715472a95ba9aeefc7bb302?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 4, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/1a979e2d9af700800c5622789b9f344d41fcde97624768d62b21e13a66ee5bbf?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 5, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/69ec04243bb68057c43bb3be743448e81c6fda42b3edccce6f0b61693ec8795f?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 6, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/13e1bc7b7ce5a282992a46483177aae84231197a56bbebf4150603af063b2cfa?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 7, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/d7483247e91632193f12425d70dcd43ef43ca35498d67f328b331bc5ab58f9a8?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 8, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/69886b02c4f618a5237f4ee83c7b94c2df96cc14a5b7917a100aa303d356b294?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 9, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/8cf7cb320bc4d19777bf49e58c1a93650c5a178aacf5b80b594ec9af75d9d062?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 10, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c1bf9f9d2871d06c3a9844c4478030d14d376d0f6787fc704a95cf0e4903d3a5?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 11, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/cc4f6c3c71f56eb1e01e16f9f3264314f17d0cafddd16afdcc44c3ac6ce57247?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 12, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/d40b33203ae08ebaa368a985668085437bd592223c98f573b8aa15c0470bff22?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 13, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c7c6b906f13c410f37641136165451e61f8bd4af0c1deb1f99edc3d195f774b4?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 14, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7f832ce42e9c4f9ff10f19af7ff2c93e4f6092bb17ab8d9e8d2525089c37ec96?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 15, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/5d3529c6cf9c0a09ed96abb3998dc6643e2946a4a715472a95ba9aeefc7bb302?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
  { id: 16, name: 'Baby Wealthy Club', price: '$17,625,107', image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/1a979e2d9af700800c5622789b9f344d41fcde97624768d62b21e13a66ee5bbf?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c' },
];

const categories = ['ALL', 'Axie', 'Accessory', 'Land', 'Item', 'Rune', 'Charm', 'Material', 'Consumable'];

function SearchNFT() {
  return (
    <main className={styles.searchNftContainer}>
      <section className={styles.searchSection}>
        <h1 className={styles.searchTitle}>Search NFT</h1>
        <div className={styles.categoryList}>
          {categories.map((category, index) => (
            <button key={index} className={index === 0 ? styles.activeCategory : styles.category}>
              {category}
            </button>
          ))}
        </div>
        <div className={styles.filterContainer}>
          <CategoryFilter />
          <PriceFilter />
          <TimeFilter />
          <StatusFilter />
        </div>
        <div className={styles.nftGrid}>
          {nftData.map((nft) => (
            <NFTCard key={nft.id} {...nft} />
          ))}
        </div>
        <Pagination />
      </section>
      <Footer />
    </main>
  );
}

export default SearchNFT;