/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './Filter.module.css';

function StatusFilter() {
  return (
    <div className={styles.statusFilter}>
      <button className={styles.activeStatus}>ALL</button>
      <button className={styles.status}>For sale</button>
      <button className={styles.status}>Sold</button>
      <button className={styles.status}>Sale</button>
      <button className={styles.status}>Ended</button>
    </div>
  );
}

export default StatusFilter;