/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TradeIndices from './TradeIndices';
import PopularCollections from './PopularCollections';
import Footer from './Footer';
import styles from './NFTMarketplace.module.css';

const NFTMarketplace = () => {
  return (
    <div className={styles.marketplaceContainer}>
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/d48fc0d57a21b41e6a95bd18e4494c2aceee797ac21f5075f5038d539d5de647?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="" className={styles.backgroundImage} />
      <div className={styles.contentWrapper}>
        {/* <Header /> */}
        <h1 className={styles.mainTitle}>NFT Marketplace for Digital Art</h1>
        <button className={styles.ctaButton}>See more</button>
      </div>
      <main className={styles.mainContent}>
        <TradeIndices />
        <PopularCollections />
      </main>
      <Footer />
    </div>
  );
};

export default NFTMarketplace;