/**
 * This code was generated by Builder.io.
 */
import React, { useState } from 'react';
import styles from './TradeIndices.module.css';

const TradeIndices = () => {
  const categories = ['ALL', 'Axie', 'Accessory', 'Land', 'Item', 'Rune', 'Charm', 'Material', 'Consumable'];
  const timePeriods = ['24H', '7D', '30D'];
  const [activeCategory, setActiveCategory] = useState('ALL');
  const [activeTimePeriod, setActiveTimePeriod] = useState('24H');

  return (
    <section className={styles.tradeIndices}>
      <h2 className={styles.sectionTitle}>Trade indices</h2>
      <div className={styles.filterContainer}>
        <div className={styles.categoryFilter}>
          {categories.map((category) => (
            <button
              key={category}
              className={`${styles.filterButton} ${category === activeCategory ? styles.active : ''}`}
              onClick={() => setActiveCategory(category)}
            >
              {category}
            </button>
          ))}
        </div>
        <div className={styles.timeFilter}>
          {timePeriods.map((period) => (
            <button
              key={period}
              className={`${styles.filterButton} ${period === activeTimePeriod ? styles.active : ''}`}
              onClick={() => setActiveTimePeriod(period)}
            >
              {period}
            </button>
          ))}
        </div>
      </div>
      <TradeTable />
    </section>
  );
};

const TradeTable = () => {
  const tradeData = [
    { rank: 1, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/7fb9810bedb6d009398a516cd65a7b9b21e480b65ae796b4715eeacb91140bf0?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 2, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/4fc49343f63047876644004ac1474e9e3d98c700261a85bca067ec2cc8e9590d?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 3, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95a7a671f9c083d11fa060856b1ca282999b3dca73215d69c95211cf4042ed96?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 4, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/02e7a62349b82a12faa7a2781c3a42df73b3f49d7dd6ae2908c057daf6ce36c6?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 5, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/885eb751a3a415df28995e95a73f7aa5fcdc957b6d6a8809decb512a0cc656f7?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 6, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/8cce4312cfa29d8544c04aed26b58ada77212b1259ef36c98a9db91c662eb025?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 7, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/05935bb870e8bf88a9c9cd03d8e472cac1543f58bd543006c76a33da38d87f45?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 8, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/2f37fc92f129fb00d25dfb682363e970184e3cfea76ab4b422a1790de5dee7a9?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 9, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/29bf2853fccaab834c292d8776c8e4881ab3e1ea521be3f2f446dd371bee9841?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 10, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/2ee9f282e2a04f188c902447fabef1e93584a0cad39528684775a4fc12d32fe4?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 11, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/b03e3cd1530119d015078fd88ec39fad5df5228c0f57bba9da82702e5ada5631?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
    { rank: 12, image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/138d2c0b50f42d5cfa147d8978d13344747953241bb6f92940797f028899aeef?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c', name: 'Name collection', time: '10 hours ago', value: '$78,893.9', change: '0.78' },
  ];

  return (
    <div className={styles.tableContainer}>
      {tradeData.map((item) => (
        <div key={item.rank} className={styles.tableRow}>
          <span className={styles.rank}>{item.rank}</span>
          <img src={item.image} alt={item.name} className={styles.collectionImage} />
          <div className={styles.collectionInfo}>
            <span className={styles.collectionName}>{item.name}</span>
            <span className={styles.collectionTime}>{item.time}</span>
          </div>
          <div className={styles.collectionStats}>
            <span className={styles.collectionValue}>{item.value}</span>
            <span className={styles.collectionChange}>{item.change}</span>
          </div>
        </div>
      ))}
    </div>
  );
};

export default TradeIndices;