/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from './MintNFT.module.css';

function CollectionSelector() {
  return (
    <div className={styles.formBox}>
      <div className={styles.formHeader}>
        <div className={styles.collectionSelector}>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/29bf2853fccaab834c292d8776c8e4881ab3e1ea521be3f2f446dd371bee9841?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" className={styles.collectionIcon} alt="Collection icon" />
          <span className={styles.collectionText}>Select A Collection</span>
        </div>
        <button className={styles.createButton}>Create Collection</button>
      </div>
      <div className={styles.divider} />
    </div>
  );
}

export default CollectionSelector;
