/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from './MintNFT.module.css';

function InputField({ label, className }) {
  return (
    <div className={className}>
      <label className={styles.nameLabel}>{label}</label>
      <div className={styles.divider} />
    </div>
  );
}

export default InputField;