/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from './MintNFT.module.css';

function TagsInput() {
  return (
    <div className={styles.tagsSection}>
      <div className={styles.tagsContainer}>
        <h3 className={styles.tagsTitle}>Add Tags</h3>
          <div className={styles.tagsList}>
              <span className={styles.tag}>Tag 1</span>
              <span className={styles.tag}>Tag 2</span>
              <span className={styles.tag}>Tag 3</span>
              <button className={styles.addTagButton} aria-label="Add new tag">+</button>
          </div>
      </div>
    </div>
  );
}

export default TagsInput;
