/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './UserNFTs.module.css';

const nftItems = [
  { id: 1, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/9d0944506e813016075f74a62bdbd53f71c08d01692e68a92d25f64d85aee35e?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 2, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/2e367eebf98d28d23715c0bfb42ce77640c868e4d152a91be7c08ee604f7fb36?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 3, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/704c965cc01b44a1bb17ac0a349e04e472f5234083bf9e19f0e35ef0ea5c6c1f?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 4, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/9d0944506e813016075f74a62bdbd53f71c08d01692e68a92d25f64d85aee35e?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 5, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/2e367eebf98d28d23715c0bfb42ce77640c868e4d152a91be7c08ee604f7fb36?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 6, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/704c965cc01b44a1bb17ac0a349e04e472f5234083bf9e19f0e35ef0ea5c6c1f?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
  { id: 7, image: "https://cdn.builder.io/api/v1/image/assets/TEMP/9d0944506e813016075f74a62bdbd53f71c08d01692e68a92d25f64d85aee35e?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c", name: "Name collection" },
];

function NFTCollection() {
  return (
    <section className={styles.nftCollectionSection}>
      <div className={styles.collectionHeader}>
        <div className={styles.collectionInfo}>
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/29bf2853fccaab834c292d8776c8e4881ab3e1ea521be3f2f446dd371bee9841?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="Collection icon" className={styles.collectionIcon} />
          <div>
            <h3 className={styles.collectionName}>Name collection</h3>
            <p className={styles.collectionTimestamp}>10 hours ago</p>
          </div>
        </div>
        <button className={styles.ownButton}>I have it</button>
      </div>
      <hr className={styles.collectionDivider} />
      <div className={styles.nftGrid}>
        {nftItems.map((item) => (
          <div key={item.id} className={styles.nftItem}>
            <img src={item.image} alt={`NFT ${item.id}`} className={styles.nftImage} />
            <p className={styles.nftName}>{item.name}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

export default NFTCollection;