/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './UserNFTs.module.css';

function ProfileSettings() {
  return (
    <section className={styles.profileSettingsSection}>
      <h2 className={styles.settingsTitle}>Profile settings</h2>
      <form className={styles.settingsForm}>
        <div className={styles.formRow}>
          <div className={styles.formGroup}>
            <label htmlFor="name" className={styles.formLabel}>Modify the name</label>
            <input type="text" id="name" className={styles.formInput} placeholder="Please enter a name" />
          </div>
          <div className={styles.formGroup}>
            <label htmlFor="gender" className={styles.formLabel}>Gender</label>
            <div className={styles.selectWrapper}>
              <select id="gender" className={styles.formSelect}>
                <option value="">Please select a gender</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>
        </div>
        <div className={styles.formRow}>
          <div className={styles.formGroup}>
            <label htmlFor="link" className={styles.formLabel}>My link</label>
            <input type="url" id="link" className={styles.formInput} placeholder="My link" />
          </div>
          <div className={styles.formGroup}>
            <label htmlFor="age" className={styles.formLabel}>My age</label>
            <input type="number" id="age" className={styles.formInput} placeholder="My age" />
          </div>
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="wallet" className={styles.formLabel}>My wallet</label>
          <div className={styles.walletInputGroup}>
            <input type="text" id="wallet" className={styles.formInput} placeholder="My wallet" readOnly />
            <button type="button" className={styles.unlinkButton}>Unlink</button>
          </div>
        </div>
        <button type="submit" className={styles.saveButton}>Save the settings</button>
      </form>
    </section>
  );
}

export default ProfileSettings;