/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './NFTGenerator.module.css';

function AdvancedSection() {
  return (
    <section className={styles.advancedSection}>
      <div className={styles.advancedContent}>
        <div className={styles.settingsColumn}>
          <div className={styles.settingsWrapper}>
            <h2 className={styles.settingsTitle}>Advanced Setting</h2>
            <label htmlFor="prompt" className={styles.promptLabel}>Prompt</label>
          </div>
        </div>
        <div className={styles.descriptionColumn}>
          <textarea
            id="prompt"
            className={styles.descriptionInput}
            placeholder="Text Description of your NFT"
            aria-label="Text Description of your NFT"
          />
        </div>
      </div>
    </section>
  );
}

export default AdvancedSection;