/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './NFTGenerator.module.css';

function InputSection() {
  return (
    <section className={styles.inputSection}>
      <label htmlFor="nftName" className={styles.inputLabel}>Enter your NFT's Name</label>
      <input type="text" id="nftName" className={styles.visually_hidden} caria-label="Enter your NFT's Name" />
      <div className={styles.divider} />
    </section>
  );
}

export default InputSection;