/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './NFTGenerator.module.css';

function ModelSection() {
  return (
    <section className={styles.modelSection}>
      <div className={styles.modelHeader}>
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/29bf2853fccaab834c292d8776c8e4881ab3e1ea521be3f2f446dd371bee9841?placeholderIfAbsent=true&apiKey=f3aaf6d180294e6db6f355070af6792c" alt="" className={styles.styleIcon} />
        <h2 className={styles.modelLabel}>Choose a backbone model</h2>
      </div>
      <div className={styles.divider} />
    </section>
  );
}

export default ModelSection;