/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styles from './NFTGenerator.module.css';
import Header from './Header';
import InputSection from './InputSection';
import AdvancedSettings from './AdvancedSettings';

function NFTGenerator() {
  return (
    <main className={styles.container}>
      <div className={styles.content}>
        <Header />
        <div className={styles.mainContent}>
          <InputSection />
          <AdvancedSettings />
          <button className={styles.generateButton}>GENERATE</button>
        </div>
      </div>
    </main>
  );
}

export default NFTGenerator;